# Generated by Django 2.2.4 on 2019-09-02 20:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pw', '0003_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
